---
title: "Project Phase-1"
author: "James Gramajo"
---


1 Importacion de liberias

```{r}
# Instalar solo si no estan instalados previamnte
if(!require(arules)) install.packages("arules")
if(!require(readxl)) install.packages("readxl")
if(!require(readxl)) install.packages("fim4r")
library(arules)
library(readxl)
library(fim4r)
```


2. Cargar el conjunto de datos
```{r}

data_sindicados_unida <- read_excel("Data\\mp-sindicados-2024-2023.xlsx")
#ELiminar año_denuncia
#data_sindicados_unida <- data_sindicados_unida[, -2]

# Filtro para mantener solo las filas donde 'año_hecho' es igual a 2024
data_sindicados_2024 <- data_sindicados_unida[data_sindicados_unida$año_hecho == 2024, ]
# Filtro para mantener solo las filas donde 'año_hecho' es igual a 2023
data_sindicados_2023 <- data_sindicados_unida[data_sindicados_unida$año_hecho == 2023, ]




head(data_sindicados_unida)

```


3 Reglas de asociación Apriori

3.1 Apriori 2024 Sindicados
```{r}

# Se agregan las columnas de interes
columnas_de_interes <- c(
  "dia_sem_hecho",
  "depto_ocu_hecho",
  "zona_ocu_hecho",
  "sexo_sindicados",
  "est_conyugal",
  "delito_com",
  "principales_delitos"
)

data_subset <- data_sindicados_2024[, columnas_de_interes]

data_factores <- as.data.frame(lapply(data_subset, as.factor))
# Crear el objeto de transacciones
transactions <- as(data_factores, "transactions")

# Ejecutar el algoritmo Apriori usado en clase
rules <- apriori(transactions,
                 parameter = list(support = 0.2, confidence = 0.5, minlen = 2))
# Inspeccionar las reglas más interesantes (ordenadas por lift)
interesting_rules <- sort(rules, by = "lift", decreasing = TRUE)
inspect(head(interesting_rules, 100))
```

3.2 Apriori en 2024 Sindicados
```{r}

columnas_de_interes <- c(
  "depto_ocu_hecho",
  "mupio_ocu_hecho",

  "sexo_sindicados",
  "principales_delitos"
  )

data_subset <- data_sindicados_2024[, columnas_de_interes]

data_factores <- as.data.frame(lapply(data_subset, as.factor))

# Crear el objeto de transacciones
transactions <- as(data_factores, "transactions")

# Ejecutar el algoritmo Apriori usado en clase
rules <- apriori(transactions,
                 parameter = list(support = 0.1, confidence = 0.1, minlen = 2))
# Inspeccionar las reglas más interesantes (ordenadas por lift)
interesting_rules <- sort(rules, by = "lift", decreasing = TRUE)
inspect(head(interesting_rules, 10))
```
3.3 Apirori 2023 Sindicados
```{r}
columnas_de_interes <- c(
  "año_denuncia",
  "año_hecho",
  "delito_com",
  "depto_ocu_hecho"
  )

data_subset <- data_sindicados_2023[, columnas_de_interes]

data_factores <- as.data.frame(lapply(data_subset, as.factor))

# Crear el objeto de transacciones
transactions <- as(data_factores, "transactions")

# Ejecutar el algoritmo Apriori usado en clase
rules <- apriori(transactions,
                 parameter = list(support = 0.2, confidence = 0.4, minlen = 2))

# Inspeccionar las reglas más interesantes (ordenadas por lift)
interesting_rules <- sort(rules, by = "lift", decreasing = TRUE)
inspect(head(interesting_rules, 100))
```

4 Reglas de asociación FP-Growth
4.1 FPGrowth sindicados 2023 
```{r}

#Seleccionando columnas para analisis
data_fp <- data_sindicados_2023[, c(
  "dia_sem_hecho",
  "depto_ocu_hecho",

  "delito_com"
  
)]



reglas_fp <- fim4r(data_fp,method = "fpgrowth",target = "rules",supp = 0.2,conf = 0.5)

#Reglas en un Dataframe
rf <- as(reglas_fp, "data.frame")


rf_ordenadas <- rf[order(-rf$lift), ]

# --- 8. Mostrar las 10 reglas principales ---
head(rf_ordenadas, 20)

```
Carga de datos de agraviados para analisis
```{r}
data_agraviados_unida <- read_excel("Data\\mp-agraviados-2024-2023.xlsx")
# Filtro para mantener solo las filas donde 'año_hecho' es igual a 2024
data_agraviados_2024 <- data_agraviados_unida[data_agraviados_unida$año_hecho == 2024, ]
# Filtro para mantener solo las filas donde 'año_hecho' es igual a 2023
data_agraviados_2023 <- data_agraviados_unida[data_agraviados_unida$año_hecho == 2023, ]
```

4.2 FPGrowth agraviados 2024
```{r}

#Seleccionando columnas para analisis
data_fp <- data_agraviados_2024[, c(
  "mes_hecho",
  "dia_hecho",
  "reg_mes",
  "dia_denuncia",
  "delito_com",
  "depto_ocu_hecho"
  
)]


reglas_fp <- fim4r(data_fp,method = "fpgrowth",target = "rules",supp = 0.2,conf = 0.5)

#Reglas en un Dataframe
rf <- as(reglas_fp, "data.frame")


rf_ordenadas <- rf[order(-rf$lift), ]

# --- 8. Mostrar las 10 reglas principales ---
head(rf_ordenadas, 20)

```
